# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  ms.imaginex.co:
    site_hosts:
      - canonical: ms.imaginex.co
        redirects:
          - www.ms.imaginex.co
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: admin@imaginex.co
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
